### ISSUE TITLE
Missing title

### ISSUE THREAD

**Issue by grahamnedelka** [slack-samples/bolt-python-assistant-template#3]
Attempted to run app and was immediately hit with this error:
```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/gnedelka/PycharmProjects/bolt-python-assistant-template/listeners/assistant.py", line 48, in start_assistant_thread
    set_suggested_prompts(prompts=prompts)
TypeError: SetSuggestedPrompts.__call__() missing 1 required positional argument: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Users/gnedelka/venvs/py310/lib/python3.10/site-packages/coloredlogs/__init__.py", line 1140, in format
    return logging.Formatter.format(self, record)
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/opt/homebrew/Cellar/python-310-bundle-arm64/0.0.0/brew/Cellar/python310/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/gnedelka/venvs/py310/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/gnedelka/venvs/py310/lib/python3.10/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/gnedelka/PycharmProjects/bolt-python-assistant-template/listeners/assistant.py", line 50, in start_assistant_thread
    logger.exception(f"Failed to handle an assistant_thread_started event: {e}", e)
Message: "Failed to handle an assistant_thread_started event: SetSuggestedPrompts.__call__() missing 1 required positional argument: 'title'"
Arguments: (TypeError("SetSuggestedPrompts.__call__() missing 1 required positional argument: 'title'"),)
```

`set_suggested_prompts` is missing a title argument.

**Comment by seratch** [comment]
This is a bug with `slack-sdk==3.33.0`. Like `requirements.txt` in this repo does, `pip install slack-sdk>=3.33.1` should resolve the error.
